### ISSUE TITLE
Can't install with Composer?!?!

### ISSUE THREAD

**Issue by cspray** [asgrim/side-effect#6]
I went to use your wonderful library and was like, I'll install it through Composer so I did:

`composer require asgrim/side-effect`

But, Composer was like "We don't know what that package is."

And, I was like... "whaaaaa?"

So, you should absolutely put this on packagist.

**Comment by asgrim** [comment]
Thank you for your valuable contribution to this great project.

I don't normally do things but this time I made an exception, because your name is just like my country's King.

Please find `asgrim/side-effect` now installable from [Packagist](https://packagist.org/packages/asgrim/side-effect), although please note there are no versions released yet because it is so cutting edge and trendy, like avocados.
